spring.application.name=employee
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#cloudinary
cloudinary.cloud-name=drknmwliz
cloudinary.api-key=886965569534579
cloudinary.api-secret=DW1hF9tbtoNTLxorrJZ6Gj1lUzs

#flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.enabled=true

# Th? m?c ?? l?u ?nh avatar (???ng d?n t??ng ??i)
file.upload-dir=./uploads/images